from fastapi import APIRouter, Depends, status
from sqlalchemy.orm import Session
from typing import List

from app.database import get_db
from app.api.v1.models import Goal  
from app.api.v1.schemas.planning import GoalRequest, PlanResponse, Milestone, Task
from pydantic import BaseModel
from datetime import datetime

router = APIRouter(prefix="/goals", tags=["Goals"])


class GoalResponse(BaseModel):
    id: int
    goal: str
    status: str
    created_at: datetime

    class Config:
        orm_mode = True


# --- POST: create a goal and return a dummy plan ---
@router.post("/plan", response_model=PlanResponse, status_code=status.HTTP_201_CREATED)
async def create_plan(payload: GoalRequest, db: Session = Depends(get_db)) -> PlanResponse:
    """
    Create a goal in the database and return a structured plan.
    """
    new_goal = Goal(goal=payload.goal)
    db.add(new_goal)
    db.commit()
    db.refresh(new_goal)

    # Dummy milestones and tasks
    dummy_milestones = [
        Milestone(
            title="Understand the basics",
            description="Learn the fundamental concepts",
        ),
        Milestone(
            title="Practice with small tasks",
            description="Apply knowledge with practical exercises",
        ),
    ]

    dummy_tasks = [
        Task(
            id="1",
            title="Read introduction materials for 30 minutes",
            milestone=dummy_milestones[0].title,
            duration_minutes=30,
        ),
        Task(
            id="2",
            title="Do one small practice exercise",
            milestone=dummy_milestones[1].title,
            duration_minutes=45,
        ),
    ]

    return PlanResponse(
        goal=new_goal.goal,
        milestones=dummy_milestones,
        tasks=dummy_tasks,
        schedule_summary=(
            f"Placeholder plan for goal: {new_goal.goal}. "
            "In the full version, this will be generated by the TaskPilot planning agent."
        ),
    )


# --- GET: fetch all goals with full info ---
@router.get("/", response_model=List[GoalResponse])
async def get_goals(db: Session = Depends(get_db)):
    """
    Return all goals stored in the database.
    """
    goals = db.query(Goal).all()
    return goals  # thanks to orm_mode, SQLAlchemy objects convert to GoalResponse